## <NAME>
## 
## DESCRIPTION
## 
## Rules
## =====
##


## help:
##    Show the help.
##
rule help:
    input: "workflow/Snakefile"
    shell:
        "sed -n 's/^##//p' {input}"

## clean:                     
##    Clean all outputs
##
rule clean:
    shell:
        "rm -rf results/*"

## build_overview:
##    Print the graph.
##
rule build_overview:
  output:
    "results/method.{fileformat}"
  shell:
    """
    snakemake -c 1 --forceall --dag | dot -T{wildcards.fileformat} > {output}
    """
